version: "3"

services:
  db:
    image: postgres:13.2
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always
  api:
    volumes:
      - uploads:/app/uploads
    environment:
      - DATABASE_URL
      - SECRET_KEY_BASE
      - SECRET_KEY_GUARDIAN
      - ALLOWED_ORIGINS
      - FRONTEND_URL
      - HOST_URL
      - PORT
    restart: always
