version: "3"

services:
  db:
    extends:
      file: .docker/deploy.yml
      service: db
    container_name: bokken_prod_db
    ports:
      - ${POSTGRES_PORT}:5432
  api:
    extends:
      file: .docker/deploy.yml
      service: api
    image: coderdojobraga/bokken:latest
    container_name: bokken_prod_api
    ports:
      - ${PORT:-4001}:4001
    depends_on:
      - db

volumes:
  pgdata:
  uploads: