version: "3"

services:
  db:
    extends:
      file: .docker/deploy.yml
      service: db
    container_name: bokken_stg_db
    ports:
      - ${POSTGRES_PORT}:5432
  api:
    extends:
      file: .docker/deploy.yml
      service: api
    build:
      context: .
      args:
        - MIX_ENV=stg
    container_name: bokken_stg_api
    ports:
      - ${PORT:-4003}:4003
    depends_on:
      - db

volumes:
  pgdata:
  uploads:
