import Config

# Note we include the path to a cache manifest containing
# the digested version of static files. This manifest is
# generated by the `mix phx.digest` task, which you
# should run after static files are built and before
# starting your production server.
config :bokken, BokkenWeb.Endpoint,
  url: [
    # For production, don't forget to configure the url host
    # to something meaningful, Phoenix uses this information
    # when generating URLs.
    host: "bokken.di.uminho.pt",
    port: 80
  ],
  cache_static_manifest: "priv/static/cache_manifest.json"


config :bokken, Bokken.Mailer,
  adapter: Swoosh.Adapters.Sendinblue,
  api_key: System.get_env("MAILER_API_KEY")

# :cors_plug must be configured only in compilation time
# See https://github.com/mschae/cors_plug/issues/49 for alternative solutions
# with functions
config :cors_plug,
  origin: [
    "https://coderdojo-braga.vercel.app",
    "https://coderdojobraga.org",
    ~r/https?(.)*-cesiuminho\.vercel\.app/
  ]

# Do not print debug messages in production
config :logger, level: :info
