version: "3"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: unless-stopped
  api:
    volumes:
      - uploads:/app/priv/uploads
    environment:
      - DATABASE_URL
      - SECRET_KEY_BASE
      - SECRET_KEY_GUARDIAN
      - FRONTEND_URL
      - HOST_URL
      - PORT
    restart: unless-stopped
